### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by techtonik** [cessen/recordscreen#11]
Hello @cessen, I've added Windows support in https://github.com/cessen/recordscreen/commit/36cd334a6c0ac4a4268b31bbe5b67cf8bc023892

This requires that PR #10 is merged first.

**Comment by cessen** [comment]
Hi techtonik,
I'm looking forward to merging #10 once you address my comment (should be pretty easy, since it looks like you just have to roll back the last commit, I think).  And then these fixes for Windows support also look fantastic.

Thanks so much!
