### ISSUE TITLE
The script needs documentation

### ISSUE THREAD

**Issue by techtonik** [cessen/recordscreen#15]
Hi @cessen. People ask for documentation how to use the `recordscreen.py`. http://askubuntu.com/questions/237027/how-to-record-screen-and-internal-audio/435538?noredirect=1#comment1406910_435538

Would be nice to some PR merged.

**Comment by cessen** [comment]
Ah, that's a good point.  Yeah, we should put some examples in the readme.

**Comment by cessen** [comment]
Done in commit 262bb300a4c6dd7cefd7865e4af6124305fd08bd.

**Comment by techtonik** [comment]
Updated answer on askubuntu.
